//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPITAL.Shared.Test.CapitalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CAPITAL.Shared.Test.CapitalService.Device[] DevicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastAccessDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CAPITAL.Shared.Test.CapitalService.Device[] Devices {
            get {
                return this.DevicesField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicesField, value) != true)) {
                    this.DevicesField = value;
                    this.RaisePropertyChanged("Devices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastAccessDate {
            get {
                return this.LastAccessDateField;
            }
            set {
                if ((this.LastAccessDateField.Equals(value) != true)) {
                    this.LastAccessDateField = value;
                    this.RaisePropertyChanged("LastAccessDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueDeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((this.DeviceIdField.Equals(value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSVersion {
            get {
                return this.OSVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.OSVersionField, value) != true)) {
                    this.OSVersionField = value;
                    this.RaisePropertyChanged("OSVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueDeviceId {
            get {
                return this.UniqueDeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueDeviceIdField, value) != true)) {
                    this.UniqueDeviceIdField = value;
                    this.RaisePropertyChanged("UniqueDeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class CapitalError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DefaultPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrequencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PermissionLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DefaultPayment {
            get {
                return this.DefaultPaymentField;
            }
            set {
                if ((this.DefaultPaymentField.Equals(value) != true)) {
                    this.DefaultPaymentField = value;
                    this.RaisePropertyChanged("DefaultPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FrequencyId {
            get {
                return this.FrequencyIdField;
            }
            set {
                if ((this.FrequencyIdField.Equals(value) != true)) {
                    this.FrequencyIdField = value;
                    this.RaisePropertyChanged("FrequencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsShare {
            get {
                return this.IsShareField;
            }
            set {
                if ((this.IsShareField.Equals(value) != true)) {
                    this.IsShareField = value;
                    this.RaisePropertyChanged("IsShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PermissionLevel {
            get {
                return this.PermissionLevelField;
            }
            set {
                if ((this.PermissionLevelField.Equals(value) != true)) {
                    this.PermissionLevelField = value;
                    this.RaisePropertyChanged("PermissionLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionLevel", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    public enum PermissionLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadOnly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllowPayments = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullControl = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statement", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class Statement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PaidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaidDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatementIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPaid {
            get {
                return this.IsPaidField;
            }
            set {
                if ((this.IsPaidField.Equals(value) != true)) {
                    this.IsPaidField = value;
                    this.RaisePropertyChanged("IsPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaidDate {
            get {
                return this.PaidDateField;
            }
            set {
                if ((this.PaidDateField.Equals(value) != true)) {
                    this.PaidDateField = value;
                    this.RaisePropertyChanged("PaidDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatementId {
            get {
                return this.StatementIdField;
            }
            set {
                if ((this.StatementIdField.Equals(value) != true)) {
                    this.StatementIdField = value;
                    this.RaisePropertyChanged("StatementId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Frequency", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class Frequency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrequencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Days {
            get {
                return this.DaysField;
            }
            set {
                if ((this.DaysField.Equals(value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FrequencyId {
            get {
                return this.FrequencyIdField;
            }
            set {
                if ((this.FrequencyIdField.Equals(value) != true)) {
                    this.FrequencyIdField = value;
                    this.RaisePropertyChanged("FrequencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feedback", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class Feedback : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeedbackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedbackId {
            get {
                return this.FeedbackIdField;
            }
            set {
                if ((this.FeedbackIdField.Equals(value) != true)) {
                    this.FeedbackIdField = value;
                    this.RaisePropertyChanged("FeedbackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTypeField, value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registration", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
    [System.SerializableAttribute()]
    public partial class Registration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrationId {
            get {
                return this.RegistrationIdField;
            }
            set {
                if ((this.RegistrationIdField.Equals(value) != true)) {
                    this.RegistrationIdField = value;
                    this.RaisePropertyChanged("RegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URI {
            get {
                return this.URIField;
            }
            set {
                if ((object.ReferenceEquals(this.URIField, value) != true)) {
                    this.URIField = value;
                    this.RaisePropertyChanged("URI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CapitalService.ICapitalService")]
    public interface ICapitalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/CreateUser", ReplyAction="http://tempuri.org/ICapitalService/CreateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/CreateUserCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.User CreateUser(CAPITAL.Shared.Test.CapitalService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/Login", ReplyAction="http://tempuri.org/ICapitalService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/LoginCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.User Login(CAPITAL.Shared.Test.CapitalService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/GetAccounts", ReplyAction="http://tempuri.org/ICapitalService/GetAccountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/GetAccountsCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.Account[] GetAccounts(CAPITAL.Shared.Test.CapitalService.User source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/CreateAccount", ReplyAction="http://tempuri.org/ICapitalService/CreateAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/CreateAccountCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void CreateAccount(CAPITAL.Shared.Test.CapitalService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/UpdateAccount", ReplyAction="http://tempuri.org/ICapitalService/UpdateAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/UpdateAccountCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void UpdateAccount(CAPITAL.Shared.Test.CapitalService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/DeleteAccount", ReplyAction="http://tempuri.org/ICapitalService/DeleteAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/DeleteAccountCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void DeleteAccount(CAPITAL.Shared.Test.CapitalService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/ShareAccount", ReplyAction="http://tempuri.org/ICapitalService/ShareAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/ShareAccountCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void ShareAccount(CAPITAL.Shared.Test.CapitalService.Account account, string email, CAPITAL.Shared.Test.CapitalService.PermissionLevel permissionLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/GetStatements", ReplyAction="http://tempuri.org/ICapitalService/GetStatementsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/GetStatementsCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.Statement[] GetStatements(CAPITAL.Shared.Test.CapitalService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/GetStatementById", ReplyAction="http://tempuri.org/ICapitalService/GetStatementByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/GetStatementByIdCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.Statement GetStatementById(CAPITAL.Shared.Test.CapitalService.User user, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/UpdateStatement", ReplyAction="http://tempuri.org/ICapitalService/UpdateStatementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/UpdateStatementCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void UpdateStatement(CAPITAL.Shared.Test.CapitalService.Statement statement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/GetRecentActivity", ReplyAction="http://tempuri.org/ICapitalService/GetRecentActivityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/GetRecentActivityCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.Statement[] GetRecentActivity(CAPITAL.Shared.Test.CapitalService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/GetFrequencies", ReplyAction="http://tempuri.org/ICapitalService/GetFrequenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/GetFrequenciesCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        CAPITAL.Shared.Test.CapitalService.Frequency[] GetFrequencies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/SendFeedback", ReplyAction="http://tempuri.org/ICapitalService/SendFeedbackResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/SendFeedbackCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void SendFeedback(CAPITAL.Shared.Test.CapitalService.Feedback userFeedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/Register", ReplyAction="http://tempuri.org/ICapitalService/RegisterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/RegisterCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void Register(CAPITAL.Shared.Test.CapitalService.Registration registration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/SendTile", ReplyAction="http://tempuri.org/ICapitalService/SendTileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/SendTileCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void SendTile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/SendEmail", ReplyAction="http://tempuri.org/ICapitalService/SendEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/SendEmailCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void SendEmail(string fromUser, string subject, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICapitalService/SendToast", ReplyAction="http://tempuri.org/ICapitalService/SendToastResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CAPITAL.Shared.Test.CapitalService.CapitalError), Action="http://tempuri.org/ICapitalService/SendToastCapitalErrorFault", Name="CapitalError", Namespace="http://schemas.datacontract.org/2004/07/CAPITAL.ORM.Objects")]
        void SendToast(CAPITAL.Shared.Test.CapitalService.User user, string title, string subTitle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICapitalServiceChannel : CAPITAL.Shared.Test.CapitalService.ICapitalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CapitalServiceClient : System.ServiceModel.ClientBase<CAPITAL.Shared.Test.CapitalService.ICapitalService>, CAPITAL.Shared.Test.CapitalService.ICapitalService {
        
        public CapitalServiceClient() {
        }
        
        public CapitalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CapitalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapitalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapitalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPITAL.Shared.Test.CapitalService.User CreateUser(CAPITAL.Shared.Test.CapitalService.User user) {
            return base.Channel.CreateUser(user);
        }
        
        public CAPITAL.Shared.Test.CapitalService.User Login(CAPITAL.Shared.Test.CapitalService.User user) {
            return base.Channel.Login(user);
        }
        
        public CAPITAL.Shared.Test.CapitalService.Account[] GetAccounts(CAPITAL.Shared.Test.CapitalService.User source) {
            return base.Channel.GetAccounts(source);
        }
        
        public void CreateAccount(CAPITAL.Shared.Test.CapitalService.Account account) {
            base.Channel.CreateAccount(account);
        }
        
        public void UpdateAccount(CAPITAL.Shared.Test.CapitalService.Account account) {
            base.Channel.UpdateAccount(account);
        }
        
        public void DeleteAccount(CAPITAL.Shared.Test.CapitalService.Account account) {
            base.Channel.DeleteAccount(account);
        }
        
        public void ShareAccount(CAPITAL.Shared.Test.CapitalService.Account account, string email, CAPITAL.Shared.Test.CapitalService.PermissionLevel permissionLevel) {
            base.Channel.ShareAccount(account, email, permissionLevel);
        }
        
        public CAPITAL.Shared.Test.CapitalService.Statement[] GetStatements(CAPITAL.Shared.Test.CapitalService.User user) {
            return base.Channel.GetStatements(user);
        }
        
        public CAPITAL.Shared.Test.CapitalService.Statement GetStatementById(CAPITAL.Shared.Test.CapitalService.User user, int id) {
            return base.Channel.GetStatementById(user, id);
        }
        
        public void UpdateStatement(CAPITAL.Shared.Test.CapitalService.Statement statement) {
            base.Channel.UpdateStatement(statement);
        }
        
        public CAPITAL.Shared.Test.CapitalService.Statement[] GetRecentActivity(CAPITAL.Shared.Test.CapitalService.User user) {
            return base.Channel.GetRecentActivity(user);
        }
        
        public CAPITAL.Shared.Test.CapitalService.Frequency[] GetFrequencies() {
            return base.Channel.GetFrequencies();
        }
        
        public void SendFeedback(CAPITAL.Shared.Test.CapitalService.Feedback userFeedback) {
            base.Channel.SendFeedback(userFeedback);
        }
        
        public void Register(CAPITAL.Shared.Test.CapitalService.Registration registration) {
            base.Channel.Register(registration);
        }
        
        public void SendTile(string name) {
            base.Channel.SendTile(name);
        }
        
        public void SendEmail(string fromUser, string subject, string message) {
            base.Channel.SendEmail(fromUser, subject, message);
        }
        
        public void SendToast(CAPITAL.Shared.Test.CapitalService.User user, string title, string subTitle) {
            base.Channel.SendToast(user, title, subTitle);
        }
    }
}
